name: CI and Deploy to GitHub Pages

# Trigger the workflow on push to main branch and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9.0] # Specify Node.js version

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run unit tests
      - name: Run unit tests
      #  run: npm run test -- --watch=false --browsers=ChromeHeadlessCI ChromeHeadless",                "flags": ["--no-sandbox", "--disable-gpu"
        run: npm run test -- --watch=false --browsers=ChromeHeadlessCI --code-coverage

      # 5. Build the Angular project
      - name: Build project
        run: npm run build -- --configuration production --base-href "/Calculator/"

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/calculator # Adjust if your output path is different
          # Optionally, set the branch and folder (default is gh-pages branch and root folder)
          # branch: gh-pages
          # folder: ./
